apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ydf-app-demo-stage
  namespace: qa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: ydf-app-demo-stage
      app.kubernetes.io/name: ydf-app-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ydf-app-demo-stage
        app.kubernetes.io/name: ydf-app-demo
    spec:
      containers:
      - image: nullck/circle_helm_test:lala
        imagePullPolicy: IfNotPresent
        name: ydf-app-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 80Mi
